/* Body file for function Platform
 * Generated by TASTE on 2022-03-01 18:05:09
 * Provided interfaces : HK_Tick
 * Required interfaces : Get, Put
 * User-defined properties for this function:
 * Timers              : 
 */
#include "platform_vm_if.h"
#ifdef __unix__
   #include <stdio.h>
#endif



extern void adainit(void);

extern void init_sensors(void);
extern unsigned sensors_initialized;
extern void init_storage(void);
extern unsigned storage_initialized;
unsigned platform_initialized = 0;
void init_platform(void)
{
   if (0 == platform_initialized) {
      platform_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == sensors_initialized) {
          init_sensors();
      }
      if (0 == storage_initialized) {
          init_storage();
      }
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function Platform");
#endif
      platform_initialized = 2;
   }
}
void platform_HK_Tick()
{

   //  Directly call user code, no parameters to pass
   extern void platform_PI_HK_Tick(void);
   platform_PI_HK_Tick();
   // puts ("platform_hk_tick called");
}

