-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by Kazoo (templates/glue/language_wrappers/ri_adb/function.tmplt)
-- Date : 2022-03-01 17:18:59

package body Gssw_RI is

   procedure Tc
      (Telecommand : in out asn1SccTc_Type) is
      procedure C_Tc
         (Telecommand : in out asn1SccTc_Type)
         with Import,
              Convention => C,
              Link_Name  => "gssw_RI_TC";
   begin
         C_Tc (Telecommand);
   end Tc;

end Gssw_RI;
