/* Body file for function GSSW
 * Generated by TASTE on 2022-03-01 17:18:59
 * Provided interfaces : TM
 * Required interfaces : TC
 * User-defined properties for this function:
 * Timers              : 
 */
#include "gssw_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif



extern void adainit(void);

unsigned gssw_initialized = 0;
void init_gssw(void)
{
   if (0 == gssw_initialized) {
      gssw_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function GSSW");
#endif
      gssw_initialized = 2;
   }
}
void gssw_TM
      (const char *IN_telemetry, size_t IN_telemetry_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void gssw_PI_TM
      (const asn1SccTM_Type *);




   // Call user code
   gssw_PI_TM ((asn1SccTM_Type *)IN_telemetry);

}

