--  Generated by TASTE on 2022-03-01 18:05:09
--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD

with Native_Implementation_Dataview; use Native_Implementation_Dataview;
with Taste_Basictypes;               use Taste_Basictypes;

-- Access to required interfaces is specified in this package:
with Sensors_RI; use Sensors_RI;

package Sensors is


   procedure Get (Ad : out asn1SccAnalog_Data_Table)
      with Export,
           Convention => C,
           Link_Name  => "sensors_PI_Get";

end Sensors;
