#!/usr/bin/python3
# convert 12-bit ADC temperature sensor reading to Celsius

import sys

# parameters
V25   = 0.76;                # V at 25 C
Vref  = 2.95;                # reference voltage
Scale = 0.01;                # V/ºC
Offset = -5.6;               # ºC (experimental calibration)

range = 4096.0;              # max ADC output value (12 bit converter)

# sensor reading
R = float(sys.argv[1]);
V = R/range*Vref;

#print('{0:.0f} = {1:.3f} V'.format(R, V));

# Celsius temperature
T = (V - V25)/Scale + 25.0 + Offset;

print('{0:.0f} = {1:.1f} C'.format(R, T));
