--  Generated by TASTE on 2022-02-21 17:48:38
--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD

with Native_Implementation_Dataview; use Native_Implementation_Dataview;
with Taste_Basictypes;               use Taste_Basictypes;
with Context_Storage;

-- Access to required interfaces is specified in this package:
with Storage_RI; use Storage_RI;

package Storage is

    Capacity : asn1SccT_Uint16 := Context_Storage.Storage_Ctxt.Capacity;
    pragma Export (C, Capacity, "storage_capacity");

   procedure Get (Out_Data : out asn1SccSatellite_State)
      with Export,
           Convention => C,
           Link_Name  => "storage_PI_Get";
   
   
   procedure Put (In_Data : in out asn1SccSatellite_State)
      with Export,
           Convention => C,
           Link_Name  => "storage_PI_Put";

end Storage;
