/* Message identifiers for the GUI messages
 * Used by the code of the GUIs and by the ctypes Python interface
 * DO NOT EDIT THIS FILE MANUALLY - MODIFY THE KAZOO TEMPLATE IF NECESSARY
*/
#pragma once

// 2 poll, tm
typedef enum {
   i_TM
} T_gssw_PI_list;

typedef enum {
   i_TC
} T_gssw_RI_list;

