--  Generated by TASTE on 2022-03-01 18:05:09
--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD

with Native_Implementation_Dataview; use Native_Implementation_Dataview;
with Taste_Basictypes;               use Taste_Basictypes;

-- Access to required interfaces is specified in this package:
with Platform_RI; use Platform_RI;

package Platform is


   procedure Hk_Tick
      with Export,
           Convention => C,
           Link_Name  => "platform_PI_HK_Tick";

end Platform;
