--  Stub generated by OpenGEODE.
--  You can edit this file, it will not be overwritten

package body Manager_RI is
   procedure HK_Task is null;
   procedure TM_Error (Contents : in out asn1SccTM_Error_Contents) is null;
   procedure TM_Mode (op_mode : in out asn1SccOperating_Mode) is null;
   procedure SET_Coverage_Timer (Val : in out asn1SccT_UInt32) is null;
   procedure RESET_Coverage_Timer is null;
end Manager_RI;