/* Body file for function Sensors
 * Generated by TASTE on 2022-03-01 18:05:09
 * Provided interfaces : Get
 * Required interfaces : 
 * User-defined properties for this function:
 * Timers              : 
 */
#include "sensors_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif



extern void adainit(void);

unsigned sensors_initialized = 0;
void init_sensors(void)
{
   if (0 == sensors_initialized) {
      sensors_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function Sensors");
#endif
      sensors_initialized = 2;
   }
}
void sensors_Get
      (char *OUT_ad, size_t *OUT_ad_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sensors_PI_Get
      (asn1SccAnalog_Data_Table *);




   // Call user code
   sensors_PI_Get ((asn1SccAnalog_Data_Table *)OUT_ad);

}

