--  Generated by TASTE on 2022-03-01 17:18:59
--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD

with Native_Implementation_Dataview; use Native_Implementation_Dataview;
with Taste_Basictypes;               use Taste_Basictypes;

-- Access to required interfaces is specified in this package:
with Gssw_RI; use Gssw_RI;

package Gssw is


   procedure Tm (Telemetry : in out asn1SccTm_Type)
      with Export,
           Convention => C,
           Link_Name  => "gssw_PI_TM";

end Gssw;
