--  Body file for function GSSW
--  Generated by TASTE on 2022-03-01 00:15:58
--  You can edit this file, it will not be overwritten
--  Provided interfaces : TM
--  Required interfaces : TC
--  Timers              : 

with Ada.Text_IO; use Ada.Text_IO;

package body Gssw is

   procedure Tm (Telemetry : in out asn1SccTm_Type) is
   
      begin
         --  Write your code here
         null;
      end Tm;


begin
   Put_Line("[GSSW] Started.");
end Gssw;

