--  Generated by TASTE on 2022-03-01 18:05:09
--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD

with Native_Implementation_Dataview; use Native_Implementation_Dataview;
with Taste_Basictypes;               use Taste_Basictypes;

-- Access to required interfaces is specified in this package:
with Measurer_And_Actuator_RI; use Measurer_And_Actuator_RI;

package Measurer_And_Actuator is


   procedure Tick
      with Export,
           Convention => C,
           Link_Name  => "measurer_and_actuator_PI_Tick";

end Measurer_And_Actuator;
