--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
--  Generated by TASTE (Kazoo template templates/skeletons/ada-ri-source/function.tmplt)
--  2022-03-01 18:05:09
with Native_Implementation_Dataview; use Native_Implementation_Dataview;
with Taste_Basictypes;               use Taste_Basictypes;
with adaasn1rtl;

package Measurer_And_Actuator_RI is

   procedure Read_Mgm (Bbt : out asn1SccT_B_B_T);
   
   
   procedure Step (Bbt : in out asn1SccT_B_B_T; Omega : in out asn1SccT_Omega; K_Pb : in out asn1SccT_Float; K_Pe : in out asn1SccT_Float; M_M : in out asn1SccT_Float; Mt_Working : in out asn1SccT_Mt_Working; Control : out asn1SccT_Control);
   
   
   procedure Control_Mgt (Control : in out asn1SccT_Control);

   procedure Check_Queue (Res : out adaasn1rtl.Asn1Boolean)
      with Import, Convention => C, Link_Name => "measurer_and_actuator_check_queue";
end Measurer_And_Actuator_RI;
