-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by Kazoo (templates/glue/language_wrappers/ri_adb/function.tmplt)
-- Date : 2022-03-01 18:05:09

package body Ttc_RI is

   procedure Current_Mode
      (Current : out asn1SccOperating_Mode) is
      procedure C_Current_Mode
         (Current : out asn1SccOperating_Mode)
         with Import,
              Convention => C,
              Link_Name  => "ttc_RI_Current_Mode";
   begin
         C_Current_Mode (Current);
   end Current_Mode;
   
   
   
   procedure Get
      (Out_Data : out asn1SccSatellite_State) is
      procedure C_Get
         (Out_Data : out asn1SccSatellite_State)
         with Import,
              Convention => C,
              Link_Name  => "ttc_RI_Get";
   begin
         C_Get (Out_Data);
   end Get;
   
   
   
   procedure Last
      (Out_Data : out asn1SccSatellite_State) is
      procedure C_Last
         (Out_Data : out asn1SccSatellite_State)
         with Import,
              Convention => C,
              Link_Name  => "ttc_RI_Last";
   begin
         C_Last (Out_Data);
   end Last;
   
   
   
   procedure Process_Tc
      (Tc : in out asn1SccTc_Type) is
      procedure C_Process_Tc
         (Tc : in out asn1SccTc_Type)
         with Import,
              Convention => C,
              Link_Name  => "ttc_RI_Process_TC";
   begin
         C_Process_Tc (TC);
   end Process_Tc;
   
   
   
   procedure Tm
      (Telemetry : in out asn1SccTm_Type) is
      procedure C_Tm
         (Telemetry : in out asn1SccTm_Type)
         with Import,
              Convention => C,
              Link_Name  => "ttc_RI_TM";
   begin
         C_Tm (Telemetry);
   end Tm;

end Ttc_RI;
