/* Body file for function TTC
 * Generated by TASTE on 2022-03-01 18:05:09
 * Provided interfaces : HK_Task, TC, TM_Basic_Task, TM_Error, TM_Mode
 * Required interfaces : Current_Mode, Get, Last, Process_TC, TM
 * User-defined properties for this function:
 * Timers              : 
 */
#include "ttc_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif



extern void adainit(void);

extern void init_manager(void);
extern unsigned manager_initialized;
extern void init_storage(void);
extern unsigned storage_initialized;
extern void init_storage(void);
extern unsigned storage_initialized;
extern void init_manager(void);
extern unsigned manager_initialized;
unsigned ttc_initialized = 0;
void init_ttc(void)
{
   if (0 == ttc_initialized) {
      ttc_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == manager_initialized) {
          init_manager();
      }
      if (0 == storage_initialized) {
          init_storage();
      }
      if (0 == storage_initialized) {
          init_storage();
      }
      if (0 == manager_initialized) {
          init_manager();
      }
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function TTC");
#endif
      ttc_initialized = 2;
   }
}
void ttc_HK_Task()
{

   //  Directly call user code, no parameters to pass
   extern void ttc_PI_HK_Task(void);
   ttc_PI_HK_Task();
   // puts ("ttc_hk_task called");
}


void ttc_TC
      (const char *IN_telecommand, size_t IN_telecommand_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void ttc_PI_TC
      (const asn1SccTC_Type *);




   // Call user code
   ttc_PI_TC ((asn1SccTC_Type *)IN_telecommand);

}


void ttc_TM_Basic_Task()
{

   //  Directly call user code, no parameters to pass
   extern void ttc_PI_TM_Basic_Task(void);
   ttc_PI_TM_Basic_Task();
   // puts ("ttc_tm_basic_task called");
}


void ttc_TM_Error
      (const char *IN_contents, size_t IN_contents_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void ttc_PI_TM_Error
      (const asn1SccTM_Error_Contents *);




   // Call user code
   ttc_PI_TM_Error ((asn1SccTM_Error_Contents *)IN_contents);

}


void ttc_TM_Mode
      (const char *IN_op_mode, size_t IN_op_mode_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void ttc_PI_TM_Mode
      (const asn1SccOperating_Mode *);




   // Call user code
   ttc_PI_TM_Mode ((asn1SccOperating_Mode *)IN_op_mode);

}

