--  Generated by TASTE on 2022-03-01 18:05:09
--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD

with Native_Implementation_Dataview; use Native_Implementation_Dataview;
with Taste_Basictypes;               use Taste_Basictypes;

-- Access to required interfaces is specified in this package:
with Ttc_RI; use Ttc_RI;

package Ttc is


   procedure Hk_Task
      with Export,
           Convention => C,
           Link_Name  => "ttc_PI_HK_Task";
   
   
   procedure Tc (Telecommand : in out asn1SccTc_Type)
      with Export,
           Convention => C,
           Link_Name  => "ttc_PI_TC";
   
   
   procedure Tm_Basic_Task
      with Export,
           Convention => C,
           Link_Name  => "ttc_PI_TM_Basic_Task";
   
   
   procedure Tm_Error (Contents : in out asn1SccTm_Error_Contents)
      with Export,
           Convention => C,
           Link_Name  => "ttc_PI_TM_Error";
   
   
   procedure Tm_Mode (Op_Mode : in out asn1SccOperating_Mode)
      with Export,
           Convention => C,
           Link_Name  => "ttc_PI_TM_Mode";

end Ttc;
