--  Body file for function Blink_Led
--  Generated by TASTE on 2022-03-23 00:20:08
--  You can edit this file, it will not be overwritten
--  Provided interfaces : Tick
--  Required interfaces : 
--  Timers              : 

package body Blink_Led is

   Led   : asn1SccLED;
   Index : asn1SccLEDs_index := asn1SccLEDs_index'First;
   
   -- Auxiliary procedures:
   
   --------------
   -- Next_Led --
   --------------
   -- Updates the current LED (Led global variable).
   -- The new LED is the next one from the Pattern defined in the data view. The index
   -- is incremented in a modular manner; i.e.: 0, 1, 2, 3, 0, 1, ...
   procedure Next_Led is
   begin
      if Index = asn1SccLEDs_index'Last then
         Index := asn1SccLEDs_index'First;
      else
         Index := Index + 1;
      end if;
      
      Led := Pattern.Data(Index);
   end Next_Led;
   
   -- PIs implementation:

   ----------
   -- Tick --
   ----------
   
   procedure Tick is
   begin
      Clear_Led (Led);
      Next_Led;
      Set_Led (Led);
   end Tick;   
   
begin
   null;
end Blink_Led;

