--  Generated by TASTE on 2022-03-01 18:05:09
--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD

with Native_Implementation_Dataview; use Native_Implementation_Dataview;
with Taste_Basictypes;               use Taste_Basictypes;

-- Access to required interfaces is specified in this package:
with Simulated_Acs_Hw_RI; use Simulated_Acs_Hw_RI;

package Simulated_Acs_Hw is


   procedure Read_Mgm (Bbt : out asn1SccT_B_B_T)
      with Export,
           Convention => C,
           Link_Name  => "simulated_acs_hw_PI_Read_MGM";
   
   
   procedure Control_Mgt (Control : in out asn1SccT_Control)
      with Export,
           Convention => C,
           Link_Name  => "simulated_acs_hw_PI_control_MGT";

end Simulated_Acs_Hw;
