// Autogenerated code (from TASTE/Kazoo) : DO NOT EDIT
#pragma once
#include "dataview-uniq.h"
#include <assert.h>

typedef enum {
   manager_Coverage_Timer
} demo_timer_manager_timers;

static struct {
   long long value;
   enum {inactive, active} state;
} timers[1] = {{ .value = 0, .state = inactive }};

void demo_timer_manager_startup(void);
void demo_timer_manager_PI_Tick(void);

void demo_timer_manager_PI_SET_manager_Coverage_Timer(asn1SccT_UInt32 *val);
void demo_timer_manager_PI_RESET_manager_Coverage_Timer(void);

#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
