// Autogenerated code (from TASTE/Kazoo) : DO NOT EDIT

#include "demo_timer_manager.h"

// When manager_Coverage_Timer expires, this function is called:
extern void demo_timer_manager_RI_manager_Coverage_Timer(void);

void demo_timer_manager_startup(void)
{
 // Timer start up (nothing to do)
}

void demo_timer_manager_PI_Tick(void)
{
   if (active == timers[manager_Coverage_Timer].state && 0 == -- timers[manager_Coverage_Timer].value) {
      demo_timer_manager_RI_manager_Coverage_Timer();
      timers[manager_Coverage_Timer].state = inactive;
   }

}

void demo_timer_manager_PI_SET_manager_Coverage_Timer(asn1SccT_UInt32 *val)
{
   /* Timer value must be multiple of 10 ms */
   assert (0 == (*val % 10));
   timers[manager_Coverage_Timer].state = active;
   timers[manager_Coverage_Timer].value = *val / 10;
}

void demo_timer_manager_PI_RESET_manager_Coverage_Timer(void)
{
   timers[manager_Coverage_Timer].state = inactive;
}


