/* Body file for function Manager
 * Generated by TASTE on 2022-02-23 14:28:08
 * Provided interfaces : Coverage_Timer, Current_Mode, Process_TC
 * Required interfaces : HK_Task, RESET_Coverage_Timer, SET_Coverage_Timer, TM_Error, TM_Mode
 * User-defined properties for this function:
 * Timers              : Coverage_Timer
 */
#include "manager_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif



extern void adainit(void);

extern void init_demo_timer_manager(void);
extern unsigned demo_timer_manager_initialized;
extern void init_demo_timer_manager(void);
extern unsigned demo_timer_manager_initialized;
unsigned manager_initialized = 0;
void init_manager(void)
{
   if (0 == manager_initialized) {
      manager_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == demo_timer_manager_initialized) {
          init_demo_timer_manager();
      }
      if (0 == demo_timer_manager_initialized) {
          init_demo_timer_manager();
      }
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function Manager");
#endif
      manager_initialized = 2;
   }
}
void manager_Coverage_Timer()
{

   //  Directly call user code, no parameters to pass
   extern void manager_PI_Coverage_Timer(void);
   manager_PI_Coverage_Timer();
   // puts ("manager_coverage_timer called");
}


void manager_Current_Mode
      (char *OUT_current, size_t *OUT_current_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void manager_PI_Current_Mode
      (asn1SccOperating_Mode *);




   // Call user code
   manager_PI_Current_Mode ((asn1SccOperating_Mode *)OUT_current);

}


void manager_Process_TC
      (const char *IN_tc, size_t IN_tc_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void manager_PI_Process_TC
      (const asn1SccTC_Type *);




   // Call user code
   manager_PI_Process_TC ((asn1SccTC_Type *)IN_tc);

}

