/* ASN.1 System configuration file for function Manager
 * Generated by TASTE on 2022-03-01 18:05:09
 */
#define __NEED_Operating_Mode_NATIVE


#define __NEED_TC_Type_NATIVE
#define __NEED_T_UInt32_NATIVE


#define __NEED_TM_Error_Contents_NATIVE


#define __NEED_Operating_Mode_NATIVE
