/* Header file for function Manager in SDL language
 * Generated by TASTE on 2022-02-23 14:28:08
 * Context Parameters present : NO
 * Provided interfaces : Coverage_Timer, Current_Mode, Process_TC
 * Required interfaces : HK_Task, RESET_Coverage_Timer, SET_Coverage_Timer, TM_Error, TM_Mode
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#ifdef __cplusplus
extern "C" {
#endif


// Function initialization - calls user startup code of all dependent functions
void init_manager(void);


/* Provided interfaces */
void manager_Coverage_Timer(void);


void manager_Current_Mode
      (char *OUT_current, size_t *OUT_current_len);



void manager_Process_TC
      (const char *IN_tc, size_t IN_tc_len);


#ifdef __cplusplus
}
#endif

