-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by Kazoo (templates/glue/language_wrappers/ri_adb/function.tmplt)
-- Date : 2022-02-23 14:28:08

package body Manager_RI is

   procedure Hk_Task is
      procedure C_Hk_Task
         with Import,
              Convention => C,
              Link_Name  => "manager_RI_HK_Task";
   begin
         C_Hk_Task;
   end Hk_Task;
   
   
   
   procedure Reset_Coverage_Timer is
      procedure C_Reset_Coverage_Timer
         with Import,
              Convention => C,
              Link_Name  => "manager_RI_RESET_Coverage_Timer";
   begin
         C_Reset_Coverage_Timer;
   end Reset_Coverage_Timer;
   
   
   
   procedure Set_Coverage_Timer
      (Val : in out asn1SccT_Uint32) is
      procedure C_Set_Coverage_Timer
         (Val : in out asn1SccT_Uint32)
         with Import,
              Convention => C,
              Link_Name  => "manager_RI_SET_Coverage_Timer";
   begin
         C_Set_Coverage_Timer (Val);
   end Set_Coverage_Timer;
   
   
   
   procedure Tm_Error
      (Contents : in out asn1SccTm_Error_Contents) is
      procedure C_Tm_Error
         (Contents : in out asn1SccTm_Error_Contents)
         with Import,
              Convention => C,
              Link_Name  => "manager_RI_TM_Error";
   begin
         C_Tm_Error (Contents);
   end Tm_Error;
   
   
   
   procedure Tm_Mode
      (Op_Mode : in out asn1SccOperating_Mode) is
      procedure C_Tm_Mode
         (Op_Mode : in out asn1SccOperating_Mode)
         with Import,
              Convention => C,
              Link_Name  => "manager_RI_TM_Mode";
   begin
         C_Tm_Mode (op_mode);
   end Tm_Mode;

end Manager_RI;
