/* ASN.1 System configuration file for function Measurer_And_Actuator
 * Generated by TASTE on 2022-03-01 18:05:09
 */

#define __NEED_T_B_b_T_NATIVE


#define __NEED_T_B_b_T_NATIVE
#define __NEED_T_Omega_NATIVE
#define __NEED_T_Float_NATIVE
#define __NEED_T_Float_NATIVE
#define __NEED_T_Float_NATIVE
#define __NEED_T_MT_Working_NATIVE
#define __NEED_T_Control_NATIVE


#define __NEED_T_Control_NATIVE
