-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by Kazoo (templates/glue/language_wrappers/ri_adb/function.tmplt)
-- Date : 2022-03-01 18:05:09

package body Measurer_And_Actuator_RI is

   procedure Read_Mgm
      (Bbt : out asn1SccT_B_B_T) is
      procedure C_Read_Mgm
         (Bbt : out asn1SccT_B_B_T)
         with Import,
              Convention => C,
              Link_Name  => "measurer_and_actuator_RI_Read_MGM";
   begin
         C_Read_Mgm (BBT);
   end Read_Mgm;
   
   
   
   procedure Step
      (Bbt : in        out asn1SccT_B_B_T;
       Omega : in      out asn1SccT_Omega;
       K_Pb : in       out asn1SccT_Float;
       K_Pe : in       out asn1SccT_Float;
       M_M : in        out asn1SccT_Float;
       Mt_Working : in out asn1SccT_Mt_Working;
       Control :       out asn1SccT_Control) is
      procedure C_Step
         (Bbt : in        out asn1SccT_B_B_T;
          Omega : in      out asn1SccT_Omega;
          K_Pb : in       out asn1SccT_Float;
          K_Pe : in       out asn1SccT_Float;
          M_M : in        out asn1SccT_Float;
          Mt_Working : in out asn1SccT_Mt_Working;
          Control :       out asn1SccT_Control)
         with Import,
              Convention => C,
              Link_Name  => "measurer_and_actuator_RI_Step";
   begin
         C_Step (BBT, Omega, K_PB, K_PE, M_M, MT_Working, Control);
   end Step;
   
   
   
   procedure Control_Mgt
      (Control : in out asn1SccT_Control) is
      procedure C_Control_Mgt
         (Control : in out asn1SccT_Control)
         with Import,
              Convention => C,
              Link_Name  => "measurer_and_actuator_RI_control_MGT";
   begin
         C_Control_Mgt (control);
   end Control_Mgt;

end Measurer_And_Actuator_RI;
