/* Body file for function Measurer_And_Actuator
 * Generated by TASTE on 2022-03-01 18:05:09
 * Provided interfaces : Tick
 * Required interfaces : Read_MGM, Step, control_MGT
 * User-defined properties for this function:
 * Timers              : 
 */
#include "measurer_and_actuator_vm_if.h"
#ifdef __unix__
   #include <stdio.h>
#endif



extern void adainit(void);

extern void init_simulated_acs_hw(void);
extern unsigned simulated_acs_hw_initialized;
extern void init_acs_algorithm(void);
extern unsigned acs_algorithm_initialized;
extern void init_simulated_acs_hw(void);
extern unsigned simulated_acs_hw_initialized;
unsigned measurer_and_actuator_initialized = 0;
void init_measurer_and_actuator(void)
{
   if (0 == measurer_and_actuator_initialized) {
      measurer_and_actuator_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == simulated_acs_hw_initialized) {
          init_simulated_acs_hw();
      }
      if (0 == acs_algorithm_initialized) {
          init_acs_algorithm();
      }
      if (0 == simulated_acs_hw_initialized) {
          init_simulated_acs_hw();
      }
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function Measurer_And_Actuator");
#endif
      measurer_and_actuator_initialized = 2;
   }
}
void measurer_and_actuator_Tick()
{

   //  Directly call user code, no parameters to pass
   extern void measurer_and_actuator_PI_Tick(void);
   measurer_and_actuator_PI_Tick();
   // puts ("measurer_and_actuator_tick called");
}

