/* Header file for function ACS_Algorithm in QGenAda language
 * Generated by TASTE on 2022-03-01 18:05:09
 * Context Parameters present : NO
 * Provided interfaces : Step
 * Required interfaces : 
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#ifdef __cplusplus
extern "C" {
#endif


// Function initialization - calls user startup code of all dependent functions
void init_acs_algorithm(void);

extern void adainit(void);

/* Provided interfaces */
void acs_algorithm_Step
      (const char *IN_bbt, size_t IN_bbt_len,
       const char *IN_omega, size_t IN_omega_len,
       const char *IN_k_pb, size_t IN_k_pb_len,
       const char *IN_k_pe, size_t IN_k_pe_len,
       const char *IN_m_m, size_t IN_m_m_len,
       const char *IN_mt_working, size_t IN_mt_working_len,
       char *OUT_control, size_t *OUT_control_len);


#ifdef __cplusplus
}
#endif

