/* Body file for function Storage
 * Generated by TASTE on 2022-03-01 18:05:09
 * Provided interfaces : Get, Last, Put
 * Required interfaces : 
 * User-defined properties for this function:
 * Timers              : 
 */
#include "storage_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif



extern void adainit(void);

unsigned storage_initialized = 0;
void init_storage(void)
{
   if (0 == storage_initialized) {
      storage_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function Storage");
#endif
      storage_initialized = 2;
   }
}
void storage_Get
      (char *OUT_out_data, size_t *OUT_out_data_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void storage_PI_Get
      (asn1SccSatellite_State *);




   // Call user code
   storage_PI_Get ((asn1SccSatellite_State *)OUT_out_data);

}


void storage_Last
      (char *OUT_out_data, size_t *OUT_out_data_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void storage_PI_Last
      (asn1SccSatellite_State *);




   // Call user code
   storage_PI_Last ((asn1SccSatellite_State *)OUT_out_data);

}


void storage_Put
      (const char *IN_in_data, size_t IN_in_data_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void storage_PI_Put
      (const asn1SccSatellite_State *);




   // Call user code
   storage_PI_Put ((asn1SccSatellite_State *)IN_in_data);

}

