/* ASN.1 System configuration file for function Storage
 * Generated by TASTE on 2022-03-01 18:05:09
 */
#define __NEED_Satellite_State_NATIVE


#define __NEED_Satellite_State_NATIVE


#define __NEED_Satellite_State_NATIVE

