/* Body file for function demo_Timer_Manager
 * Generated by TASTE on 2022-03-01 18:05:09
 * Provided interfaces : RESET_manager_Coverage_Timer, SET_manager_Coverage_Timer, Tick
 * Required interfaces : manager_Coverage_Timer
 * User-defined properties for this function:
 * Timers              : manager_Coverage_Timer
 */
#include "demo_timer_manager_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned demo_timer_manager_initialized = 0;
void init_demo_timer_manager(void)
{
   if (0 == demo_timer_manager_initialized) {
      demo_timer_manager_initialized = 1;
      // Call user code startup function
      extern void demo_timer_manager_startup(void);
      demo_timer_manager_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function demo_Timer_Manager");
#endif
      demo_timer_manager_initialized = 2;
   }
}
void demo_timer_manager_RESET_manager_Coverage_Timer()
{

   //  Directly call user code, no parameters to pass
   extern void demo_timer_manager_PI_RESET_manager_Coverage_Timer(void);
   demo_timer_manager_PI_RESET_manager_Coverage_Timer();
   // puts ("demo_timer_manager_reset_manager_coverage_timer called");
}


void demo_timer_manager_SET_manager_Coverage_Timer
      (const char *IN_val, size_t IN_val_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void demo_timer_manager_PI_SET_manager_Coverage_Timer
      (const asn1SccT_UInt32 *);




   // Call user code
   demo_timer_manager_PI_SET_manager_Coverage_Timer ((asn1SccT_UInt32 *)IN_val);

}


void demo_timer_manager_Tick()
{

   //  Directly call user code, no parameters to pass
   extern void demo_timer_manager_PI_Tick(void);
   demo_timer_manager_PI_Tick();
   // puts ("demo_timer_manager_tick called");
}

