/* Header file for function demo_Timer_Manager in Timer_Manager language
 * Generated by TASTE on 2022-03-01 18:05:09
 * Context Parameters present : NO
 * Provided interfaces : RESET_manager_Coverage_Timer, SET_manager_Coverage_Timer, Tick
 * Required interfaces : manager_Coverage_Timer
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#ifdef __cplusplus
extern "C" {
#endif


// Function initialization - calls user startup code of all dependent functions
void init_demo_timer_manager(void);


/* Provided interfaces */
void demo_timer_manager_RESET_manager_Coverage_Timer(void);


void demo_timer_manager_SET_manager_Coverage_Timer
      (const char *IN_val, size_t IN_val_len);



void demo_timer_manager_Tick(void);


#ifdef __cplusplus
}
#endif

